org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configureondemand=true
org.gradle.parallel=true
org.gradle.vfs.watch=true

# https://developer.android.com/build/releases/agp-9-0-0-release-notes
android.r8.strictFullModeForKeepRules=false
#android.r8.optimizedResourceShrinking=false
