[versions]
androidGradlePlugin = "8.10.0-alpha06"
# https://plugins.gradle.org/plugin/org.jetbrains.kotlin.android
androidKotlinPlugin = "2.1.0"

# https://developer.android.com/jetpack/androidx/versions

androidxActivity = "1.10.0"
androidxAnnotation = '1.9.1'
androidxAppcompat = '1.7.0'
androidxConstraintlayout = '2.2.0'
androidxCoordinatorlayout = "1.2.0"
androidxCore = '1.15.0'
androidxCustomview = "1.2.0-alpha02"
androidxDocumentfile = "1.1.0-alpha01"
androidxDrawerlayout = "1.2.0"
androidxFragment = "1.8.6"
androidxLifecycle = '2.8.7'
androidxPreference = "1.2.1"
androidxRecyclerview = "1.4.0"
androidxRoom = "2.6.1"

# https://github.com/google/desugar_jdk_libs/blob/master/CHANGELOG.md
desugar = "2.1.4"

# https://github.com/material-components/material-components-android/releases
material = '1.12.0'

# https://bouncycastle.org
bouncycastle = "1.80"

# https://junit.org/junit5/docs/current/user-guide/#overview
jupiter = "5.12.0"

# https://developer.android.com/jetpack/androidx/releases/test
androidxTestCore = '1.6.1'
androidxTestRunner = '1.6.2'
androidxTestRules = '1.6.1'

[libraries]
androidx-activity = { group = "androidx.activity", name = "activity-ktx", version.ref = "androidxActivity" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "androidxAnnotation" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppcompat" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidxConstraintlayout" }
androidx-coordinatorlayout = { group = "androidx.coordinatorlayout", name = "coordinatorlayout", version.ref = "androidxCoordinatorlayout" }
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-customview = { group = "androidx.customview", name = "customview", version.ref = "androidxCustomview" }
androidx-documentfile = { group = "androidx.documentfile", name = "documentfile", version.ref = "androidxDocumentfile" }
androidx-drawerlayout = { group = "androidx.drawerlayout", name = "drawerlayout", version.ref = "androidxDrawerlayout" }
androidx-fragment = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "androidxFragment" }
androidx-lifecycle-livedata = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidx-preference = { group = "androidx.preference", name = "preference-ktx", version.ref = "androidxPreference" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "androidxRecyclerview" }
androidx-room = { group = "androidx.room", name = "room-runtime", version.ref = "androidxRoom" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidxRoom" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidxTestCore" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTestRunner" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "androidxTestRules" }

google-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
google-desugar = { group = "com.android.tools", name = "desugar_jdk_libs_nio", version.ref = "desugar" }

bouncycastle-bcprov = { group = "org.bouncycastle", name = "bcprov-jdk18on", version.ref = "bouncycastle" }
bouncycastle-bcutil = { group = "org.bouncycastle", name = "bcutil-jdk18on", version.ref = "bouncycastle" }

junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "jupiter" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "jupiter" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "jupiter" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "androidKotlinPlugin" }
java-library = { id = "java-library" }
